### ISSUE TITLE
logosc.cn/vi/的可以吗

### ISSUE THREAD

**Issue by lengwangye** [lovelinessmoe/saveLogosc#1]
https://www.logosc.cn/vi/category/8
这种vi的可以吗

**Comment by lovelinessmoe** [comment]
我又新写了个脚本，但是只能保存png，你试试

**Comment by lovelinessmoe** [comment]
https://blog.ashes.vip/2023/04/11/logosc%E7%9A%84vi%E6%B2%B9%E5%80%99%E8%84%9A%E6%9C%AC/

**Comment by lovelinessmoe** [comment]
> https://www.logosc.cn/vi/category/8 这种vi的可以吗

https://blog.ashes.vip/2023/04/11/logosc%E7%9A%84vi%E6%B2%B9%E5%80%99%E8%84%9A%E6%9C%AC/
